import type { ArtworkSceneObjectData, Text3DSceneObjectData } from './branding.js';
import type { DrawKind, DrawingStyle } from './drawing.js';
import type { ConstraintData } from './constraints.js';
import type { LightFixtureData } from './lighting.js';
import type { TrussLegType, TrussShape } from './truss.js';
import type { LedFrame } from './led.js';
import type { BoothFloorFinish, BoothSide, BoothType, BoothWallFinish } from './booth.js';
/**
 * The scene document.
 *
 * A plan's contents are one JSON document, loaded and saved whole. Nothing
 * queries across plans for individual objects, so normalising them into rows
 * would cost thousands of writes per save and buy nothing.
 *
 * Every linear value here is an integer number of **millimetres**; every angle
 * is in **degrees**. `SCENE_SCHEMA_VERSION` is written into each document so
 * migrations can be applied on read.
 */

import type { FinishMap, SurfaceFinish } from './materials.js';

import type { CameraMode, UnitSystem } from './index.js';

export const SCENE_SCHEMA_VERSION = 3;

export interface Vec3 {
  x: number;
  y: number;
  z: number;
}

export const ZERO: Vec3 = { x: 0, y: 0, z: 0 };
export const ONE: Vec3 = { x: 1, y: 1, z: 1 };

/* ── Object types ──────────────────────────────────────────────────────── */

export const SCENE_OBJECT_TYPES = [
  'catalog',
  'shape',
  'curtain',
  'tent',
  'stage',
  'text',
  'opening',
  'text3d',
  'artwork',
  'drawing',
  'truss',
  'led',
  'booth',
  'light',
  'constraint',
] as const;
export type SceneObjectType = (typeof SCENE_OBJECT_TYPES)[number];

export const SHAPE_KINDS = ['rectangle', 'square', 'circle', 'triangle', 'star', 'box'] as const;
export type ShapeKind = (typeof SHAPE_KINDS)[number];

export interface BaseSceneObject {
  id: string;
  type: SceneObjectType;
  name?: string;
  /** Members of a generated set (a Table Designer arrangement) share a groupId. */
  groupId?: string | null;
  positionMm: Vec3;
  rotationDeg: Vec3;
  scale: Vec3;
  locked?: boolean;
  hidden?: boolean;
  opacity?: number;
  /**
   * Applied surface finishes, keyed by the part they were dropped on.
   *
   * On `BaseSceneObject` rather than on the catalogue object, because a
   * material has to work on everything in the scene — a wall, a stage deck, a
   * truss, a stand fascia — and putting it anywhere narrower would mean
   * writing the same feature five times. `'*'` covers the whole object; a
   * named key covers one glTF material or one procedural surface, which is
   * what makes dropping onto a specific part behave the way it looks.
   */
  finishes?: FinishMap;
}

/** A placed catalogue model. */
export interface CatalogSceneObject extends BaseSceneObject {
  type: 'catalog';
  catalogItemId: number;
  /** Cached so the scene renders before the catalogue query resolves. */
  modelUrl?: string;
  dimensionsMm?: { width: number; depth: number; height: number };
  /**
   * Seat count and shape, cached from the catalogue for the same reason as
   * the dimensions: the seating chart has to read the layout without a
   * round trip, and a plan opened offline still needs to know what seats.
   */
  seatsDefault?: number | null;
  tableShape?: 'round' | 'rectangular' | 'other' | null;
  /**
   * Set when this placement is a generated venue shell rather than a
   * catalogue item, so applying a new venue can replace the old one and the
   * costing pass can leave the building out of the furniture bill.
   */
  venueId?: number | null;
  /** Per-material colour overrides, keyed by glTF material name. */
  materialColors?: Record<string, string>;
  textureVariationId?: number | null;
  textureTilingEnabled?: boolean;
  textureTileSizeM?: number;
  /** Set on objects generated by Table Designer so they can be re-derived. */
  generatedRole?: 'table' | 'chair' | 'linen' | 'centerpiece' | 'place-setting';
  generatedSlot?: string;
}

export interface ShapeSceneObject extends BaseSceneObject {
  type: 'shape';
  kind: ShapeKind;
  widthMm: number;
  depthMm: number;
  /** 0 keeps the shape flat on the floor plane. */
  extrudeMm: number;
  radiusMm?: number;
  fillColor: string;
  fillOpacity: number;
  borderColor: string;
  borderOpacity: number;
}

/**
 * A procedural curtain.
 *
 * Shape is driven by a 3×3 anchor grid: three row widths plus six corner
 * extents, with a centre bend and top/bottom curve.
 */
export interface CurtainSceneObject extends BaseSceneObject {
  type: 'curtain';
  topWidthMm: number;
  middleWidthMm: number;
  bottomWidthMm: number;
  heightMm: number;
  curveDepthMm: number;
  middleCurveMm: number;
  topLeftExtentMm: number;
  topRightExtentMm: number;
  middleLeftExtentMm: number;
  middleRightExtentMm: number;
  bottomLeftExtentMm: number;
  bottomRightExtentMm: number;
  foldCount: number;
  foldAmplitudeMm: number;
  orientation: 'vertical' | 'horizontal';
  color: string;
  textureAssetId?: number | null;
  fillOpacity: number;
}

export const CURTAIN_LIMITS = {
  minWidthMm: 300,
  maxWidthMm: 30_000,
  minHeightMm: 300,
  maxHeightMm: 12_000,
  minFolds: 0,
  maxFolds: 120,
  minFoldAmplitudeMm: 0,
  maxFoldAmplitudeMm: 500,
} as const;

/** Tent sidewall slot: one bay on one side. */
export interface TentSidewallSlot {
  index: number;
  side: 'north' | 'east' | 'south' | 'west';
  bay: number;
  /** null = open bay. */
  catalogItemId: number | null;
  sidewallType?: string;
}

export interface TentSceneObject extends BaseSceneObject {
  type: 'tent';
  catalogItemId: number;
  family: string;
  widthMm: number;
  lengthMm: number;
  /** Eave height; ridge/peak is derived by the tent profile. */
  eaveHeightMm: number;
  peakHeightMm: number;
  bayLengthMm: number;
  slots: TentSidewallSlot[];
  /** Hide the canopy so the interior can be laid out. */
  canopyHidden?: boolean;
  canopyColor?: string;
}

export type StageSide = 'north' | 'east' | 'south' | 'west';

/** Modular decked stage. Decks are a fixed 4' × 4' module. */
export interface StageSceneObject extends BaseSceneObject {
  type: 'stage';
  deckRows: number;
  deckColumns: number;
  deckHeightMm: number;
  stairSides: StageSide[];
  /** Which 4' bay the stair opening sits on, per side (1-indexed). */
  stairBays: Partial<Record<StageSide, number>>;
  skirtSides: StageSide[];
  guardrailSides: StageSide[];
  deckColor?: string;
  skirtColor?: string;
}

export const STAGE_DECK_SIZE_MM = 1219; // 4 ft
export const STAGE_HEIGHT_SNAP_MM = 25; // 1 in
export const STAGE_RAIL_THRESHOLD_MM = 762; // 30 in — rail type switches here
export const STAGE_STAIR_EXTRA_LEG_MM = 914; // 36 in — extra support legs above this
export const STAGE_STAIR_MIN_MM = 305; // 12 in
export const STAGE_STAIR_MAX_MM = 1778; // 70 in

export interface TextSceneObject extends BaseSceneObject {
  type: 'text';
  content: string;
  heightMm: number;
  color: string;
}

/** A door or window cut into a wall segment. */
export interface OpeningSceneObject extends BaseSceneObject {
  type: 'opening';
  catalogItemId: number;
  openingKind: 'door' | 'window';
  wallSegmentId: string;
  /** Distance along the segment from its start, to the opening centre. */
  offsetAlongMm: number;
  widthMm: number;
  heightMm: number;
  /** Sill height above floor. Doors are 0. */
  bottomMm: number;
  flipped?: boolean;
}

/* ── Branding ──────────────────────────────────────────────────────────── */

/**
 * Dimensional lettering.
 *
 * The geometry parameters live in `branding.ts` alongside the finishes and
 * presets, because they are edited together and mean nothing apart.
 */
export interface Text3DSceneObject extends BaseSceneObject, Text3DSceneObjectData {
  type: 'text3d';
}

/** A printed, projected or backlit image placed in the room. */
export interface ArtworkSceneObject extends BaseSceneObject, ArtworkSceneObjectData {
  type: 'artwork';
}

/**
 * A drafted annotation: a dimension, a zone, a cable run, a note.
 *
 * Points are plan-space millimetres, the same space walls use, so a
 * dimension measures what the editor snaps to. `elevationMm` is the height
 * it is drawn at — usually the floor, but a ceiling rig plan is drawn high.
 */
export interface DrawingSceneObject extends BaseSceneObject, DrawingStyle {
  type: 'drawing';
  drawKind: DrawKind;
  points: WallPoint[];
  elevationMm: number;
  /** Note text, and the label shown against a dimension. */
  text?: string;
  /** How far the dimension line sits off the span it measures. */
  offsetMm?: number;
}

/* ── Production objects ────────────────────────────────────────────────── */

/**
 * A truss run.
 *
 * Modelled as a path with a trim height rather than as a box, because that is
 * what it is: a goalpost, a square grid and an arch differ only in their
 * points. `packages/shared/truss.ts` derives the section list, weight and span
 * warnings from exactly these fields.
 */
export interface TrussSceneObject extends BaseSceneObject {
  type: 'truss';
  systemKey: string;
  shape: TrussShape;
  /** Path in object-local millimetres; the object's own position places it. */
  points: WallPoint[];
  closed: boolean;
  /** Height to the underside of the horizontal run. */
  trimHeightMm: number;
  legType: TrussLegType;
  /** Mass hung from this run, used by the load and rigging checks. */
  hangingLoadKg: number;
  color: string;
  /** Draw the diagonal bracing rather than plain tubes. Costs triangles. */
  showBracing: boolean;
}

/** A modular LED wall, floor or totem. */
export interface LedScreenSceneObject extends BaseSceneObject {
  type: 'led';
  panelKey: string;
  columns: number;
  rows: number;
  /** Height from the floor to the bottom of the image. */
  bottomMm: number;
  frame: LedFrame;
  /** Horizontal curvature across the whole wall, in degrees. 0 is flat. */
  curveDeg: number;
  /** Image shown on the screen, and the flat colour behind it. */
  contentUrl?: string | null;
  contentColor: string;
  /** How strongly the screen lights the room around it. */
  glowIntensity: number;
  /** Screen brightness as a fraction of the panel's rated nits. */
  brightness: number;
}

/** An exhibition stand. */
export interface BoothSceneObject extends BaseSceneObject {
  type: 'booth';
  boothType: BoothType;
  widthMm: number;
  depthMm: number;
  heightMm: number;
  walls: BoothSide[];
  wallFinish: BoothWallFinish;
  wallColor: string;
  floorFinish: BoothFloorFinish;
  floorColor: string;
  platformHeightMm: number;
  fascia: boolean;
  fasciaHeightMm: number;
  fasciaText: string;
  fasciaColor: string;
  storeRoom: boolean;
  counter: boolean;
  /** Stand number and exhibitor, printed on the hall plan. */
  standNumber?: string;
  exhibitorName?: string;
}

/** A lighting fixture. */
export interface LightFixtureSceneObject extends BaseSceneObject, LightFixtureData {
  type: 'light';
}

/** A venue constraint: a height limit, a rigging point, a supply, an exit. */
export interface ConstraintSceneObject extends BaseSceneObject, ConstraintData {
  type: 'constraint';
}

export type SceneObject =
  | CatalogSceneObject
  | ShapeSceneObject
  | CurtainSceneObject
  | TentSceneObject
  | StageSceneObject
  | TextSceneObject
  | OpeningSceneObject
  | TrussSceneObject
  | LedScreenSceneObject
  | BoothSceneObject
  | LightFixtureSceneObject
  | ConstraintSceneObject
  | Text3DSceneObject
  | ArtworkSceneObject
  | DrawingSceneObject;

/* ── Walls ─────────────────────────────────────────────────────────────── */

export interface WallPoint {
  xMm: number;
  zMm: number;
}

export interface WallSegment {
  id: string;
  spanId: string;
  start: WallPoint;
  end: WallPoint;
  thicknessMm: number;
  heightMm: number;
  color?: string;
  wallpaperTextureId?: number | null;
}

export interface FloorPolygon {
  id: string;
  points: WallPoint[];
  color?: string;
  textureAssetId?: number | null;
  textureTileSizeM?: number;
}

export interface WallBlueprint {
  segments: WallSegment[];
  floors: FloorPolygon[];
}

/* ── Groups (Table Designer output) ────────────────────────────────────── */

export interface PlaceSettingSlots {
  plate?: number | null;
  beverage?: number | null;
  beverage2?: number | null;
  fork1?: number | null;
  fork2?: number | null;
  knife?: number | null;
  spoon?: number | null;
}

export const PLACE_SETTING_SLOT_KEYS = [
  'plate',
  'beverage',
  'beverage2',
  'fork1',
  'fork2',
  'knife',
  'spoon',
] as const;
export type PlaceSettingSlotKey = (typeof PLACE_SETTING_SLOT_KEYS)[number];

export const PLACE_SETTING_SLOT_LABELS: Record<PlaceSettingSlotKey, string> = {
  plate: 'Plate',
  beverage: 'Glass',
  beverage2: 'Second glass',
  fork1: 'Fork 1',
  fork2: 'Fork 2',
  knife: 'Knife',
  spoon: 'Spoon',
};

export const LAYOUT_PRESETS = [
  'grid',
  'angled-grid',
  'rows',
  'pyramid',
  'diagonal',
  'curved',
  'circle',
  'closed-circle',
  'u-shape',
  'aisle',
] as const;
export type LayoutPreset = (typeof LAYOUT_PRESETS)[number];

export interface LayoutParams {
  preset: LayoutPreset;
  rows: number;
  columns: number;
  rowSpacingMm: number;
  columnSpacingMm: number;
  angleDeg: number;
  sweepDeg: number;
  radiusMm: number;
  itemsPerRow: number;
  itemIncrement: number;
}

export const DEFAULT_LAYOUT_PARAMS: LayoutParams = {
  preset: 'grid',
  rows: 2,
  columns: 3,
  rowSpacingMm: 2438, // 8 ft
  columnSpacingMm: 2438,
  angleDeg: 0,
  sweepDeg: 180,
  radiusMm: 5000,
  itemsPerRow: 6,
  itemIncrement: 1,
};

/**
 * A Table Designer arrangement. The objects it produced are *derived*: changing
 * the table, chair, seat count or layout re-generates every child, which is why
 * the parameters are stored rather than only the resulting objects.
 */
export interface TableGroup {
  id: string;
  tableItemId: number;
  linenItemId?: number | null;
  linenVariationId?: number | null;
  chairItemId?: number | null;
  seatsPerTable: number;
  centerpieceItemId?: number | null;
  placeSettings: PlaceSettingSlots;
  layout: LayoutParams;
  tableCount: number;
  originMm: Vec3;
  rotationDeg: number;
}

/* ── Lighting, camera, environment ─────────────────────────────────────── */

export const LIGHTING_PRESETS = [
  { key: 'venice_sunset', label: 'Sunset (Venice)', file: 'venice_sunset_1k.hdr' },
  { key: 'kiara_dawn', label: 'Dawn', file: 'kiara_1_dawn_1k.hdr' },
  { key: 'dikhololo_night', label: 'Night', file: 'dikhololo_night_1k.hdr' },
  { key: 'forest_slope', label: 'Forest', file: 'forest_slope_1k.hdr' },
  { key: 'lebombo', label: 'Lebombo', file: 'lebombo_1k.hdr' },
  { key: 'immenstadter_horn', label: 'Mountain', file: 'immenstadter_horn_1k.hdr' },
  { key: 'adams_place_bridge', label: 'Bridge', file: 'adams_place_bridge_1k.hdr' },
  { key: 'potsdamer_platz', label: 'Plaza', file: 'potsdamer_platz_1k.hdr' },
  { key: 'rooitou_park', label: 'Outdoor (Park)', file: 'rooitou_park_1k.hdr' },
  { key: 'empty_warehouse_01', label: 'Warehouse', file: 'empty_warehouse_01_1k.hdr' },
  { key: 'st_fagans_interior', label: 'Indoor', file: 'st_fagans_interior_1k.hdr' },
  { key: 'studio_small_03', label: 'Studio', file: 'studio_small_03_1k.hdr' },
] as const;

export type LightingPresetKey = (typeof LIGHTING_PRESETS)[number]['key'];

export interface SceneLighting {
  preset: LightingPresetKey;
  /**
   * An environment map dropped in from an online library.
   *
   * Takes precedence over `preset` when set. Kept as a URL rather than folded
   * into the preset list because the list is a fixed set we ship and verify,
   * and Poly Haven alone publishes several hundred more.
   */
  customHdriUrl?: string | null;
  /** Shown in the UI in place of the preset name. */
  customHdriLabel?: string | null;
  /**
   * Show the environment map itself behind the room.
   *
   * Off by default. An HDRI is primarily a *light source* — it drives every
   * reflection and the direction of every shadow — and showing it as a
   * backdrop is a separate decision, useful for a hero render and distracting
   * while laying out a floor.
   */
  showEnvironmentBackground?: boolean;
  /**
   * Rotation of the environment around the vertical axis, in degrees.
   *
   * The single most useful control an HDRI has: it aims the sun. Without it
   * you are stuck with wherever the photographer happened to be standing.
   */
  environmentRotationDeg?: number;
  /** Ground plane colour when no floor finish has been applied. */
  groundColor?: string;
  position: Vec3;
  heightZ: number;
  shadowsEnabled: boolean;
  glowEnabled: boolean;
  intensity: number;
}

export const DEFAULT_LIGHTING: SceneLighting = {
  preset: 'studio_small_03',
  customHdriUrl: null,
  customHdriLabel: null,
  showEnvironmentBackground: false,
  environmentRotationDeg: 0,
  /*
   * The studio floor beyond the plan's own — a real mid-tone rather than the
   * near-white it used to be. The backdrop gradient is derived from this, so
   * a pale value gave the whole viewport the flat white void that made a
   * finished plan read as a diagram. Around the same value as the default
   * concrete floor, so the hall appears to continue past the walls.
   */
  groundColor: '#c9ccd1',
  position: { x: 5, y: 10, z: 5 },
  heightZ: 10,
  shadowsEnabled: true,
  glowEnabled: false,
  intensity: 1,
};

export interface CameraPathPoint {
  positionMm: Vec3;
  targetMm: Vec3;
}

/**
 * A camera position somebody thought worth keeping.
 *
 * Distinct from a walkthrough shot, which is a *move* with a duration and an
 * easing, made to be rendered into a video. A view is a still vantage point —
 * "from the door", "the stage from row four", "the sponsor wall" — and its
 * whole purpose is navigation: a client opening a share link has no idea how to
 * orbit a 3D scene, and handing them five named places to stand is the
 * difference between a plan they understand and one they close.
 *
 * Stored in the document so the designer's choices travel with the plan, and
 * exposed on the share page as a strip of thumbnails at the bottom.
 */
export interface SavedView {
  id: string;
  name: string;
  /** Where the camera stands, and what it looks at. Millimetres, as always. */
  positionMm: Vec3;
  targetMm: Vec3;
  fov: number;
  /** A still captured when the view was saved, so the strip has a thumbnail. */
  thumbnailUrl?: string | null;
  /** One line the client reads before they click. */
  note?: string;
  createdAt: string;
}

export interface SceneCamera {
  mode: CameraMode;
  positionMm: Vec3;
  targetMm: Vec3;
  fov: number;
  path: CameraPathPoint[];
  pathSpeed: number;
}

export const DEFAULT_CAMERA: SceneCamera = {
  mode: 'perspective',
  positionMm: { x: 8000, y: 6000, z: 8000 },
  targetMm: ZERO,
  fov: 50,
  path: [],
  pathSpeed: 1,
};

/** A calibrated floor-plan drawing placed on the floor plane. */
export interface FloorPlanRef {
  imageUrl: string;
  fileKey: string;
  /** Millimetres of real world per image pixel — the calibration result. */
  mmPerPixel: number;
  widthPx: number;
  heightPx: number;
  originMm: Vec3;
  rotationDeg: number;
  opacity: number;
  locked: boolean;
}

export interface BackgroundRef {
  imageUrl: string;
  fileKey: string;
}

/* ── The document ──────────────────────────────────────────────────────── */

/**
 * Render settings.
 *
 * Two modes, because they answer different questions. Fast is the WebGL
 * viewport and costs nothing, so it is what someone works in. Pro is a
 * cloud raytrace that costs credits and is what goes to a client. Keeping the
 * chosen quality on the document means a re-render months later matches the
 * image that was approved.
 */
export interface SceneRenderSettings {
  /** Named look from `lighting.ts`, applied on top of the environment. */
  look: string;
  /** Overall exposure, so a dark look can be brought up without relighting. */
  exposure: number;
  /** Bloom on emissive surfaces — LED walls, neon lettering. */
  bloom: number;
  /** Haze density; beams are invisible without it. */
  haze: number;
  /** Ambient occlusion contact shadows. Costs frames on weak hardware. */
  contactShadows: boolean;
  /** Export width for a still. 3840 is the "4K render" the brief asks for. */
  exportWidth: number;
  exportHeight: number;
  /** Background treatment behind the room. */
  backdrop: 'environment' | 'studio' | 'transparent' | 'color';
  backdropColor: string;
}

export const DEFAULT_RENDER_SETTINGS: SceneRenderSettings = {
  look: 'corporate-summit',
  exposure: 1,
  bloom: 0.35,
  haze: 0.1,
  contactShadows: true,
  exportWidth: 3840,
  exportHeight: 2160,
  backdrop: 'environment',
  backdropColor: '#0b1220',
};

/**
 * A camera move.
 *
 * A walkthrough is a list of shots rather than a single spline, because that is
 * how anyone describes one: "start wide at the entrance, push in on the stage,
 * orbit the centrepiece". Each shot owns its own duration and easing, so
 * changing one does not retime the rest.
 */
export const CAMERA_SHOT_KINDS = ['static', 'dolly', 'orbit', 'flythrough', 'crane', 'reveal'] as const;
export type CameraShotKind = (typeof CAMERA_SHOT_KINDS)[number];

export const CAMERA_EASINGS = ['linear', 'ease-in-out', 'ease-out', 'ease-in'] as const;
export type CameraEasing = (typeof CAMERA_EASINGS)[number];

export interface CameraShot {
  id: string;
  name: string;
  kind: CameraShotKind;
  fromMm: Vec3;
  toMm: Vec3;
  lookAtMm: Vec3;
  /** Second look-at, so a move can pan as it travels. */
  lookAtEndMm?: Vec3;
  durationMs: number;
  easing: CameraEasing;
  fov: number;
  /** Orbit only: how far around the subject the move sweeps. */
  sweepDeg?: number;
  /** Hold on the last frame before the next shot starts. */
  holdMs?: number;
}

export interface SceneWalkthrough {
  shots: CameraShot[];
  /** Movement speed in fly-through mode, in metres per second. */
  flySpeed: number;
  /** Eye height when walking the room rather than flying it. */
  eyeHeightMm: number;
  /** Loop the sequence when it reaches the end. */
  loop: boolean;
  /** Ambient bed chosen for an exported video. */
  music: 'none' | 'ambient' | 'uplifting' | 'cinematic' | 'energetic';
  /** Export shape: landscape for a deck, vertical for a reel. */
  aspect: 'landscape' | 'square' | 'vertical';
}

export const DEFAULT_WALKTHROUGH: SceneWalkthrough = {
  shots: [],
  flySpeed: 2.5,
  eyeHeightMm: 1650,
  loop: true,
  music: 'none',
  aspect: 'landscape',
};

export interface SceneDocument {
  schemaVersion: number;
  units: UnitSystem;
  objects: SceneObject[];
  tableGroups: TableGroup[];
  walls: WallBlueprint;
  lighting: SceneLighting;
  camera: SceneCamera;
  floorPlan?: FloorPlanRef | null;
  background?: BackgroundRef | null;
  gridSizeMm: number;
  showGrid: boolean;
  snapToGrid: boolean;
  rotationSnapDeg: number;
  /* ── Added in schema 2 ─────────────────────────────────────────────── */
  /** Market this plan is built for; drives truss stock, materials and rules. */
  regionCode: string;
  /** Rate card used to cost the plan. Null falls back to the built-in rates. */
  rateCardId: number | null;
  render: SceneRenderSettings;
  walkthrough: SceneWalkthrough;
  /** Warn when two objects occupy the same space. Off by default: a chair
   *  tucked under a table is not a mistake, and nobody wants to be told. */
  collisionCheck: boolean;
  /** Show the constraint layer over the plan. */
  showConstraints: boolean;

  /* ── Added in schema 3 ─────────────────────────────────────────────── */
  /**
   * Named camera positions, in the order the designer wants them shown.
   *
   * Empty by default: a plan with no views behaves exactly as it always has,
   * and the strip on the share page simply does not appear.
   */
  views?: SavedView[];

  /**
   * The finish on the floor of the whole plan.
   *
   * At document level rather than per floor polygon, because "carpet the
   * room" is one decision a designer makes once and the take-off prices by
   * area — splitting it across polygons would make both harder for no gain.
   * Null leaves the floor as it is: an open hall floor, or the venue's own.
   */
  floorFinish?: SurfaceFinish | null;
}

/**
 * What a new plan stands on.
 *
 * Grey event carpet, because it is what is actually rolled out under most of
 * the work this tool is used for, and because a plan that opens on a flat
 * near-white void reads as a diagram rather than a room — furniture with
 * nothing under it looks like it is floating whatever else the renderer does.
 *
 * Mid-tone rather than the pale concrete slab tried first: a light grey floor
 * sits close enough to full exposure that shadows have nowhere left to darken,
 * so the room stayed flat no matter how the lighting was balanced. This has
 * somewhere to go, which is what makes the contact shadows read.
 *
 * Replaced the moment a designer picks a different floor, and priced by area
 * with everything else — see the Floor control on the bottom toolbar.
 */
export const DEFAULT_FLOOR_FINISH: SurfaceFinish = {
  materialId: 'builtin:carpet-grey',
  label: 'Event carpet, grey',
  source: 'Novira',
  license: 'Included',
  colorHex: '#63676d',
  roughness: 0.96,
  metalness: 0,
  tileMm: 800,
};

export function createEmptyScene(units: UnitSystem = 'imperial'): SceneDocument {
  return {
    schemaVersion: SCENE_SCHEMA_VERSION,
    units,
    objects: [],
    tableGroups: [],
    walls: { segments: [], floors: [] },
    floorFinish: { ...DEFAULT_FLOOR_FINISH },
    lighting: { ...DEFAULT_LIGHTING },
    camera: { ...DEFAULT_CAMERA, path: [] },
    floorPlan: null,
    background: null,
    gridSizeMm: units === 'metric' ? 500 : 305,
    showGrid: true,
    snapToGrid: false,
    rotationSnapDeg: 10,
    // This deployment is a single business's own tool rather than a
    // multi-tenant product with users spread across markets, and that
    // business is in Tanzania — so a new plan starts priced and specified
    // for the market it is actually built in, rather than a generic global
    // placeholder nobody there was asking for. A company with its own
    // region set (see `Company.regionCode`) overrides this regardless.
    regionCode: 'tanzania',
    rateCardId: null,
    render: { ...DEFAULT_RENDER_SETTINGS },
    walkthrough: { ...DEFAULT_WALKTHROUGH, shots: [] },
    collisionCheck: false,
    showConstraints: true,
    views: [],
  };
}

/**
 * Bring an older document up to the current schema.
 *
 * Every field added since schema 1 has a default, so an older document is
 * migrated purely by filling the gaps — nothing is rewritten and nothing is
 * lost. That is deliberate: a plan saved before these features existed must
 * open unchanged, and the reverse case (a new document read by old code) never
 * happens because the version travels with the row.
 *
 * Schema 3 added per-part surface finishes to every object. A document without
 * them is not missing anything — an object with no finishes renders in its own
 * colours, exactly as it did before — so the migration leaves the field absent
 * rather than writing an empty map onto every object in the file.
 */
export function migrateScene(input: unknown): SceneDocument {
  const base = createEmptyScene();
  if (!input || typeof input !== 'object') return base;
  const doc = input as Partial<SceneDocument>;
  return {
    ...base,
    ...doc,
    schemaVersion: SCENE_SCHEMA_VERSION,
    objects: Array.isArray(doc.objects) ? doc.objects : [],
    tableGroups: Array.isArray(doc.tableGroups) ? doc.tableGroups : [],
    walls: {
      segments: Array.isArray(doc.walls?.segments) ? doc.walls.segments : [],
      floors: Array.isArray(doc.walls?.floors) ? doc.walls.floors : [],
    },
    lighting: { ...base.lighting, ...(doc.lighting ?? {}) },
    camera: { ...base.camera, ...(doc.camera ?? {}) },
    render: { ...base.render, ...(doc.render ?? {}) },
    walkthrough: {
      ...base.walkthrough,
      ...(doc.walkthrough ?? {}),
      shots: Array.isArray(doc.walkthrough?.shots) ? doc.walkthrough.shots : [],
    },
    regionCode: typeof doc.regionCode === 'string' ? doc.regionCode : base.regionCode,
    rateCardId: typeof doc.rateCardId === 'number' ? doc.rateCardId : null,
    collisionCheck: typeof doc.collisionCheck === 'boolean' ? doc.collisionCheck : base.collisionCheck,
    views: Array.isArray(doc.views) ? doc.views : [],
    showConstraints: typeof doc.showConstraints === 'boolean' ? doc.showConstraints : base.showConstraints,
  };
}
