import { useMemo } from 'react';
import { generateLayout, type LayoutPreset } from '@novira/shared';

/**
 * A small drawing of what an arrangement will produce.
 *
 * Generated by running the real `generateLayout` and plotting the positions it
 * returns, rather than being drawn by hand. That matters for one reason: a
 * hand-drawn icon is a promise the code can quietly stop keeping. If the aisle
 * spacing changes, this picture changes with it.
 *
 * "Rows" and "Grid" are different things, and so are "Arc", "Curved" and
 * "Circle" — from the words alone nobody can tell which is which, which is
 * exactly why the picture is worth the pixels.
 */

const VIEW = 64;
const SAMPLE_COUNT = 12;

export function LayoutDiagram({
  preset,
  active,
  className = '',
}: {
  preset: LayoutPreset;
  active?: boolean;
  className?: string;
}) {
  const points = useMemo(() => {
    /*
     * Nominal parameters. The shape of an arrangement is what is being shown,
     * not its size, so these are chosen to make the form legible at 64 px
     * rather than to match any particular plan.
     */
    const placements = generateLayout(SAMPLE_COUNT, {
      preset,
      rows: 3,
      columns: 4,
      rowSpacingMm: 1800,
      columnSpacingMm: 1800,
      angleDeg: 30,
      sweepDeg: preset === 'closed-circle' ? 360 : 180,
      radiusMm: 4200,
      itemsPerRow: 4,
      itemIncrement: 1,
    });

    if (!placements.length) return [];

    // Fit whatever came back into the viewbox, with a margin.
    const xs = placements.map((p) => p.positionMm.x);
    const zs = placements.map((p) => p.positionMm.z);
    const minX = Math.min(...xs);
    const maxX = Math.max(...xs);
    const minZ = Math.min(...zs);
    const maxZ = Math.max(...zs);

    const spanX = Math.max(1, maxX - minX);
    const spanZ = Math.max(1, maxZ - minZ);
    const span = Math.max(spanX, spanZ);
    const margin = 9;
    const scale = (VIEW - margin * 2) / span;

    // Centre the cloud rather than anchoring it, so an off-centre arrangement
    // like a U still sits in the middle of its own icon.
    const offsetX = (VIEW - spanX * scale) / 2;
    const offsetZ = (VIEW - spanZ * scale) / 2;

    return placements.map((p) => ({
      x: (p.positionMm.x - minX) * scale + offsetX,
      y: (p.positionMm.z - minZ) * scale + offsetZ,
      rotation: p.rotationDeg,
    }));
  }, [preset]);

  if (!points.length) return null;

  return (
    <svg
      viewBox={`0 0 ${VIEW} ${VIEW}`}
      className={className}
      aria-hidden
      role="presentation"
    >
      {points.map((p, i) => (
        <rect
          key={i}
          x={p.x - 3.4}
          y={p.y - 3.4}
          width={6.8}
          height={6.8}
          rx={1.6}
          // Rotation is shown because several arrangements differ only by how
          // the items face — an angled grid and a plain grid put things in the
          // same places.
          transform={`rotate(${p.rotation} ${p.x} ${p.y})`}
          className={active ? 'fill-primary' : 'fill-ink-subtle'}
          opacity={active ? 0.95 : 0.7}
        />
      ))}
    </svg>
  );
}
