/**
 * Build and register the procedural catalogue items.
 *
 * These are generated from real rental dimensions rather than fetched, so they
 * still go through `inspectGltfFile` afterwards — a generator bug that produced
 * a table of the wrong size should be caught by the same check that catches a
 * mislabelled download, not trusted because we wrote it.
 */
import { CATALOG_CATEGORIES } from '@novira/shared';
import { prisma } from '../lib/prisma.js';
import { PROCEDURAL_ITEMS } from '../services/proceduralAssets.js';
import { inspectGltfFile } from '../services/gltfInspect.js';
import { env } from '../lib/env.js';
import path from 'node:path';

async function main() {
  for (const c of CATALOG_CATEGORIES) {
    await prisma.catalogCategory.upsert({
      where: { slug: c.slug },
      create: { slug: c.slug, name: c.name, sortOrder: c.order },
      update: { name: c.name, sortOrder: c.order },
    });
  }
  const categories = new Map(
    (await prisma.catalogCategory.findMany()).map((r) => [r.slug, r.id])
  );

  let built = 0;
  let mismatched = 0;

  for (const spec of PROCEDURAL_ITEMS) {
    const categoryId = categories.get(spec.categorySlug);
    if (!categoryId) {
      console.warn(`[procedural] unknown category "${spec.categorySlug}" for ${spec.key}`);
      continue;
    }

    const { url, triangles } = await spec.build();

    // Verify the generator produced what it claimed, in millimetres.
    const relative = url.split('/static/assets/')[1] ?? '';
    const facts = await inspectGltfFile(path.join(env.assetDir, relative));
    const measuredW = Math.round(Math.max(facts.sizeRaw.x, facts.sizeRaw.z) * 1000);
    const measuredH = Math.round(facts.sizeRaw.y * 1000);
    const wOff = Math.abs(measuredW - spec.widthMm);
    const hOff = Math.abs(measuredH - spec.heightMm);
    const ok = wOff <= 3 && hOff <= 3;
    if (!ok) {
      mismatched += 1;
      console.warn(
        `[procedural] ${spec.key}: generated ${measuredW}×${measuredH} mm but declared ${spec.widthMm}×${spec.heightMm} mm`
      );
    }

    await prisma.catalogItem.upsert({
      where: { id: (await prisma.catalogItem.findFirst({ where: { sourceKey: 'procedural', sourceAssetId: spec.key }, select: { id: true } }))?.id ?? -1n },
      create: {
        categoryId,
        scope: 'global',
        name: spec.name,
        description: spec.description,
        modelUrl: url,
        widthMm: spec.widthMm,
        depthMm: spec.depthMm,
        heightMm: spec.heightMm,
        diameterMm: spec.diameterMm ?? null,
        tableShape: spec.tableShape ?? null,
        seatsDefault: spec.seats ?? null,
        isFreePlanAvailable: spec.freePlan ?? false,
        triangleCount: triangles,
        sourceKey: 'procedural',
        sourceLabel: 'Novira',
        sourceAssetId: spec.key,
        license: 'Novira original',
        attribution: 'Generated by Novira from rental dimensions',
        reviewStatus: ok ? 'approved' : 'pending',
        verifiedAt: new Date(),
        verificationScore: ok ? 100 : 40,
        verificationNotes: JSON.parse(
          JSON.stringify({
            verdict: ok ? 'publish' : 'review',
            summary: ok
              ? `Generated at exactly ${spec.widthMm}×${spec.depthMm}×${spec.heightMm} mm and measured back the same.`
              : `Generator output ${measuredW}×${measuredH} mm did not match the declared size.`,
            measured: { widthMm: measuredW, heightMm: measuredH },
            declared: { widthMm: spec.widthMm, heightMm: spec.heightMm },
            triangles,
          })
        ),
      },
      update: {
        categoryId,
        name: spec.name,
        description: spec.description,
        modelUrl: url,
        widthMm: spec.widthMm,
        depthMm: spec.depthMm,
        heightMm: spec.heightMm,
        diameterMm: spec.diameterMm ?? null,
        tableShape: spec.tableShape ?? null,
        seatsDefault: spec.seats ?? null,
        triangleCount: triangles,
        reviewStatus: ok ? 'approved' : 'pending',
        verifiedAt: new Date(),
      },
    });

    built += 1;
    console.log(
      `[procedural] ${ok ? '✓' : '?'} ${spec.name} — ${measuredW}×${measuredH} mm, ${triangles} tris`
    );
  }

  console.log(`\n[procedural] built ${built} items (${mismatched} size mismatches).`);
  await prisma.$disconnect();
}

main().catch(async (err) => {
  console.error('[procedural] failed:', err);
  await prisma.$disconnect();
  process.exit(1);
});
